<?php

require_once 'PHPUnit/Framework.php';

require_once __DIR__ . '/../complexNumber.php';

/**
 * Test class for ComplexNumberPHP.
 * Generated by PHPUnit on 2011-01-02 at 13:43:44.
 */
class ComplexNumberPHPTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ComplexNumberPHP
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ComplexNumberPHP(1, 2);
	}

	public function testAddition() {
		$number = new ComplexNumberPHP(3, 4);
	 	$result = $this->object->add($number);
		$expected = new ComplexNumberPHP(4, 6);
		$this->assertEquals($expected, $result);
	}

	public function testSubtract() {
		$number = new ComplexNumberPHP(3, 4);
	 	$result = $this->object->subtract($number);
		$expected = new ComplexNumberPHP(-2, -2);
		$this->assertEquals($expected, $result);
	}
	
	public function testMultiplyBy() {
		//	    (a+bi)(c+di) = (ac - bd) + (bc + ad)i
		$number = new ComplexNumberPHP(3, 4);
	 	$result = $this->object->multiplyBy($number);
		$expected = new ComplexNumberPHP(-5, 10);
		$this->assertEquals($expected, $result);
	}

	public function testDivideBy() {
		//	    (a+bi)(c+di) = (ac - bd) + (bc + ad)i
		$first = new ComplexNumberPHP(2, 6);
		$number = new ComplexNumberPHP(4, 1);
	 	$result = $first->divideBy($number);
		$expected = new ComplexNumberPHP(14/17, 22/17);
		$this->assertEquals($expected, $result);
	}

	public function testSquare() {
	 	$result = $this->object->square();
		$expected = new ComplexNumberPHP(-3, 4);
		$this->assertEquals($expected, $result);
	}

}
