<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../pallete.php';

/**
 * Test class for Pallette.
 * Generated by PHPUnit on 2011-01-02 at 10:11:07.
 */
class PalletteTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Pallette
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Pallette;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @todo Implement testOffsetSet().
	 */
	public function testOffsetSet() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testOffsetExists().
	 */
	public function testOffsetExists() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testOffsetUnset().
	 */
	public function testOffsetUnset() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testOffsetGet().
	 */
	public function testOffsetGet() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}

?>
